version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: node-miner_web_1
      APP_PORT: 5000
      
  web:
    image: node-miner:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 10s
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      TZ: "Etc/UTC"
    networks:
      default:
        ipv4_address: $APP_NODE_MINER_WEB_IP
