services:
  web:
    image: btcdataguy/node-miner:latest
    container_name: btcdataguy-apps-node-miner_web_1
    restart: on-failure
    stop_grace_period: 10s
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      TZ: "Etc/UTC"
