version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_BTCDATAGUY_APPS_NODE_MINER_WEB_IP
      APP_PORT: $APP_BTCDATAGUY_APPS_NODE_MINER_WEB_PORT
    container_name: btcdataguy-apps-node-miner_app_proxy_1
  
  web:
    image: btcdataguy/node-miner:latest
    container_name: btcdataguy-apps-node-miner_web_1
    restart: on-failure
    stop_grace_period: 10s
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      TZ: "Etc/UTC"
    networks:
      default:
        ipv4_address: $APP_BTCDATAGUY_APPS_NODE_MINER_WEB_IP
